
# userphotos
userphotos.path=file:/home/pi/healthML/userphotos/

logging.level.org.springframework.web=ERROR
logging.level.com.example=INFO

# ?? Flask ??? ?? (Ubuntu)
uploads.path=file:/home/pi/flask-api/uploads/