services:
  flask-api:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_USER: wade
      DB_PASSWORD: password
      DB_HOST: 192.168.2.23
      DB_NAME: healthProject
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
    restart: always